---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-16.04-chef-12
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      product_name: chef
      product_version: 12.12
  - name: opscode-ubuntu-16.04-chef-14
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      product_name: chef
      product_version: latest
  - name: opscode-ubuntu-14.04-chef-12
    driver:
      box: bento/ubuntu-14.04
    provisioner:
      product_name: chef
      product_version: 12.12

suites:
  - name: default
    run_list:
      - recipe[barito-agent::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      barito-agent:
        sources:
          - type: 'tail'
            name: 'barito-test'
            path: '/var/log/dpkg.log'
            pos_file: '/etc/td-agent/dpkg.pos'
            parse:
              '@type': 'none'
        matches:
          - type: barito_vm
            name: 'barito-test'
            application_secret: '123456'
            produce_url: 'https://barito-router.local/produce'
            buffer:
              flush_mode: immediate
        groups: ['root']
